#
# Autor: Fernando Lewandowski Albuquerque fernando.lewandowski@gmail.com https://github.com/lewandowski/project-euler
#
#Problem 2
#19 October 2001
#
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#
#Answer: 
#
#
class Problem2
  
  def initialize maximum_value
    @maximum_value = maximum_value
  end
  
  def sum
    
    sum = 0
    
    (@maximum_value-1).downto(0) do |current_value|
      if (current_value % 3 == 0) || (current_value % 5 == 0)
        sum += current_value
      end
    end
    
    sum    
    
  end
  
end

puts "Sum is #{Problem1.new(1000).sum}"